server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_PASSWORD}
    password: ${DBMS_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true